name: dsadas
description: Simple architecture pattern for flutter apps.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

# [State Management & Routing]
  get: ^4.6.5

# [Local Storage]
  get_storage: ^2.1.1

# [Remote Storage]
  dio: ^5.0.3
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.
    - assets/gifs/.
    - assets/icons/.
    - assets/images/.

  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/roboto/Roboto-Thin.ttf
        weight: 200
      - asset: assets/fonts/roboto/Roboto-Light.ttf
        weight: 200
      - asset: assets/fonts/roboto/Roboto-Regular.ttf
        weight: 200
      - asset: assets/fonts/roboto/Roboto-Medium.ttf
        weight: 300
      - asset: assets/fonts/roboto/Roboto-Bold.ttf
        weight: 600
      - asset: assets/fonts/roboto/Roboto-Italic.ttf
        style: italic
  - family: Mulish
    fonts:
      - asset: assets/fonts/mulish/Mulish-Black.ttf
        weight: 900
      - asset: assets/fonts/mulish/Mulish-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: assets/fonts/mulish/Mulish-Bold.ttf
        weight: 600
      - asset: assets/fonts/mulish/Mulish-BoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/mulish/Mulish-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/mulish/Mulish-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/mulish/Mulish-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/mulish/Mulish-Italic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/mulish/Mulish-Light.ttf
        weight: 200
      - asset: assets/fonts/mulish/Mulish-Regular.ttf
        weight: 400
      - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
        weight: 500